//LOCALHOST
GET http://localhost:3000/contacts HTTP/1.1
###
GET http://localhost:8080/contacts/644428dfabbe0ec032bce5d6 HTTP/1.1
###
GET http://localhost:8080/contacts/644428ead0e2cb0519e3f6c2 HTTP/1.1

//PRODUCTION Deploy
GET https://ryanalvordcit341.onrender.com/contacts HTTP/1.1
###
GET https://ryanalvordcit341.onrender.com/contacts/644428dfabbe0ec032bce5d6 HTTP/1.1
###
GET https://ryanalvordcit341.onrender.com/contacts/644428ead0e2cb0519e3f6c2 HTTP/1.1
### 
GET https://ryanalvordcit341.onrender.com/contacts/6444291bd0e2cb0519e3f6c3 HTTP/1.1

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}